### ISSUE TITLE
DLL更新エラー

### ISSUE THREAD

**Issue by omiyama** [kuramochia/ToraCon-Helper#20]
DLLの更新で失敗しました
![スクリーンショット 2024-09-22 222315](https://github.com/user-attachments/assets/051e4efe-99d7-4e1d-908e-0295f183029a)

**Comment by kuramochia** [comment]
ありがとうございます。修正しますー。

**Comment by kuramochia** [comment]
[v1.6.1.0](https://github.com/kuramochia/ToraCon-Helper/releases/tag/v1.6.1.0) で修正しました。
