### ISSUE TITLE
ウィンカー自動解除

### ISSUE THREAD

**Issue by omiyama** [kuramochia/ToraCon-Helper#5]
・左ウィンカーを出して左に45度回して、右に90度以上回しても左ウィンカー消えない
・左ウィンカーを出して右に90度以上回しても左ウィンカー消えない
これは実車でもそうかもしれませんのでバグとは言えませんが、私のプログラムでは消してたので制御方法が違うんだなーってことで。実車から言うと私のプログラムの方がバグなのか？ｗｗ
これは想定された動きなんですね。

**Comment by kuramochia** [comment]
@omiyama ありがとうございます。
これ、私も「どうだったっけ？」と思いながら今の仕様で組みました。
どなたか実車の仕様がわかる人がいれば、正解を教えてほしいです。。。

**Comment by kuramochia** [comment]
@omiyama さんのおっしゃる動作が正しいみたいなので、#6 と一緒に修正します。

**Comment by kuramochia** [comment]
v1.1.1.0 で修正しました。
