### ISSUE TITLE
ウィンカーレバー、ウィンカーONにするとすぐにOFFにされる時がある

### ISSUE THREAD

**Issue by omiyama** [kuramochia/ToraCon-Helper#6]
何度も左ウィンカー出す→左にハンドル回す→右に90度以上回す→左ウィンカーが解除される
この一連の動きを何度もさせていたところ、ハンドルを触らず左ウィンカーを出したとき、すぐに左ウィンカーが解除される現象。
「ウィンカー戻す動作を実車に近づける」の右ウィンカー出して左にレバー倒したときと動作が同じ感じ（一度チカッとしてからレバーが戻る）だったので「ウィンカー戻す動作を実車に近づける」をOFFにしてやってみましたが、それでも同じことが起こりました。でもこの現象がでるタイミングがわかりませんでした。たまに出る感じです。気にせずもう一回左レバー入れるだけでOKなのでこちらも気にしなくても良いかも。
なんか重箱の隅つついてるみたいでごめんなさい。自分のプログラムでもどうも色々試してしまう癖で。。

**Comment by kuramochia** [comment]
@omiyama ありがとうございます。これは前回の値を保持している関連のバグっぽいですね。確認します。

**Comment by kuramochia** [comment]
原因判明。 #5 と一緒に修正します。

**Comment by kuramochia** [comment]
v1.1.1.0 で修正しました。
